import { LegalDocument, LegalSection } from '../components/LegalDocument'

export function PrivacyPage() {
  return <LegalDocument eyebrow="Privacy" title="Privacy Policy" summary="This policy describes information WantCove may process, why it is used, and the choices available to users.">
    <LegalSection title="1. Scope"><p>This policy applies to WantCove’s website and product-discovery service. It does not apply to a retailer or other third-party site reached through a product link; that party’s privacy policy controls its collection and use.</p></LegalSection>
    <LegalSection title="2. Information processed"><p>WantCove offers an optional like feature without requiring an account. If you allow preferences, Amazon Web Services creates a pseudonymous guest identity and WantCove stores that identity together with the product identifier and an expiration time in Amazon DynamoDB. The like request does not send WantCove a raw IP address as the like identifier.</p><p>WantCove also uses browser storage to remember your privacy choice and, when permitted, your light or dark theme. Hosting and security providers may separately process ordinary technical records such as IP address, browser or device information, requested pages, timestamps, and security events to deliver and protect the service.</p><p>If account and collection features are enabled later, WantCove may process an email address, authentication identifiers, account settings, saved products, collection names, and notes you choose to provide. If affiliate links are enabled, WantCove and an affiliate network or retailer may process link-click and referral information, including a code in the destination URL.</p></LegalSection>
    <LegalSection title="3. How information is used"><p>Information may be used to remember your display preferences, maintain your product likes, provide and secure WantCove, prevent abuse, diagnose errors, understand service performance, meet legal obligations, and administer disclosed affiliate relationships.</p></LegalSection>
    <LegalSection title="4. Sharing"><p>WantCove uses Amazon Web Services for hosting, authentication identity, GraphQL APIs, and database storage. WantCove may also share information when required by law or necessary to protect rights and safety, or as part of a properly disclosed business transaction. WantCove does not currently sell personal information for money. This statement must be reviewed before adding advertising, cross-context behavioral tracking, data brokerage, or new analytics vendors.</p></LegalSection>
    <LegalSection title="5. Cookies, local storage, and choices"><p>WantCove does not intentionally set advertising cookies. The privacy-choice record is essential storage used to remember your selection. Choosing “Allow preferences” permits persistent theme storage and anonymous like synchronization through an AWS guest identity. Choosing “Essential only” keeps theme changes and likes in the current browser session and prevents guest-like API calls. You can reopen Privacy choices from the footer.</p><p>A retailer or affiliate network may use its own cookies or similar technology after you leave WantCove. This policy and the consent experience must be updated before WantCove adds non-essential analytics, advertising, or personalization technology.</p></LegalSection>
    <LegalSection title="6. Retention and security"><p>Anonymous like records are set to expire approximately 180 days after they are created or refreshed and are removed when you unlike the product, subject to DynamoDB’s asynchronous expiration process and backup retention. Changing to Essential only stops future cloud synchronization but does not immediately delete an existing record. WantCove uses administrative and technical safeguards appropriate to the information processed, including server-derived identity keys and database recovery protection, but no system is completely secure.</p></LegalSection>
    <LegalSection title="7. Choices and rights"><p>You can decline preference storage and cloud-synchronized likes, change the theme, unlike a product, or reopen the privacy controls from the footer. Depending on where you live, you may also have rights to access, correct, delete, or obtain a copy of personal information, or to opt out of certain sharing or targeted advertising. A verified request channel and jurisdiction-specific notices must be added before Production collects personal information from covered residents.</p></LegalSection>
    <LegalSection title="8. Children"><p>WantCove is not directed to children under 13, and the service is not designed to knowingly collect their personal information. Age and consent requirements must be reviewed before opening accounts.</p></LegalSection>
    <LegalSection title="9. Changes"><p>WantCove will update this policy before materially changing what information is collected, how it is used or shared, how long it is kept, the service providers involved, or the choices offered. Material revisions will receive a new effective date.</p></LegalSection>
    <LegalSection title="10. Contact"><p>A monitored privacy request method and the legal identity of the WantCove operator will be published here before Beta enables accounts or commercial affiliate links.</p></LegalSection>
  </LegalDocument>
}
