import { LegalDocument, LegalSection } from '../components/LegalDocument'

export function PrivacyPage() {
  return <LegalDocument eyebrow="Privacy" title="Privacy Policy" summary="This policy describes information WantCove may process, why it is used, and the choices available to users.">
    <LegalSection title="1. Scope"><p>This policy applies to WantCove’s website and product-discovery service. It does not apply to a retailer or other third-party site reached through a product link; that party’s privacy policy controls its collection and use.</p></LegalSection>
    <LegalSection title="2. Information processed"><p>The local pre-release version does not offer public accounts or active affiliate links. When hosted, infrastructure providers may process basic technical records such as IP address, browser or device information, requested pages, timestamps, and security events.</p><p>If account and collection features are enabled, WantCove may process an email address, authentication identifiers, account settings, saved products, collection names, and notes you choose to provide. If affiliate links are enabled, WantCove and an affiliate network or retailer may process link-click and referral information, including a code in the destination URL.</p></LegalSection>
    <LegalSection title="3. How information is used"><p>Information may be used to provide and secure WantCove, authenticate users, maintain private saved collections, diagnose errors, prevent abuse, understand service performance, meet legal obligations, and administer disclosed affiliate relationships.</p></LegalSection>
    <LegalSection title="4. Sharing"><p>WantCove may share information with service providers that host, secure, or operate the service; when required by law or necessary to protect rights and safety; or as part of a properly disclosed business transaction. WantCove does not currently sell personal information for money. This statement must be reviewed before adding advertising, cross-context behavioral tracking, data brokerage, or new analytics vendors.</p></LegalSection>
    <LegalSection title="5. Cookies and tracking"><p>The current application does not intentionally set advertising cookies. Hosting and security providers may use essential technologies needed to deliver the service. A retailer or affiliate network may use its own cookies or similar technology after you leave WantCove. Cookie consent and this policy must be updated before WantCove adds non-essential analytics, advertising, or personalization technology.</p></LegalSection>
    <LegalSection title="6. Retention and security"><p>WantCove will retain information only as long as reasonably needed for the stated purposes, legal obligations, security, and dispute resolution. Specific retention periods and account-deletion behavior must be documented before accounts launch. WantCove uses administrative and technical safeguards appropriate to the information processed, but no system is completely secure.</p></LegalSection>
    <LegalSection title="7. Choices and rights"><p>Depending on where you live, you may have rights to access, correct, delete, or obtain a copy of personal information, or to opt out of certain sharing or targeted advertising. A verified request channel and jurisdiction-specific notices must be added before Production and before collecting personal information from covered residents.</p></LegalSection>
    <LegalSection title="8. Children"><p>WantCove is not directed to children under 13, and the service is not designed to knowingly collect their personal information. Age and consent requirements must be reviewed before opening accounts.</p></LegalSection>
    <LegalSection title="9. Changes"><p>WantCove will update this policy before materially changing what information is collected, how it is used or shared, how long it is kept, the service providers involved, or the choices offered. Material revisions will receive a new effective date.</p></LegalSection>
    <LegalSection title="10. Contact"><p>A monitored privacy request method and the legal identity of the WantCove operator will be published here before Beta enables accounts or commercial affiliate links.</p></LegalSection>
  </LegalDocument>
}
