import { LegalDocument, LegalSection } from '../components/LegalDocument'

export function TermsPage() {
  return <LegalDocument eyebrow="Legal" title="Terms of Service" summary="These terms explain the rules for browsing WantCove and using its product-discovery and saved-collection features.">
    <LegalSection title="1. Using WantCove"><p>By accessing WantCove, you agree to these Terms. If you do not agree, do not use the service. WantCove is intended for people who can legally enter into these Terms. Additional eligibility language will be added before accounts are opened.</p></LegalSection>
    <LegalSection title="2. Product discovery, not a retailer"><p>WantCove helps users discover and save products. WantCove does not currently sell, manufacture, ship, warrant, or process payment for the products shown. Product descriptions, prices, ratings, availability, and images are informational and may change. Verify material details with the retailer before purchasing.</p></LegalSection>
    <LegalSection title="3. External and affiliate links"><p>Some product links may include an affiliate or referral code. If you click one of those links and make a purchase, WantCove may receive a commission at no additional cost to you. Affiliate compensation does not increase the price charged by WantCove because WantCove is not the seller.</p><p>Clicking a retailer link takes you away from WantCove. The retailer’s own terms, privacy policy, pricing, fulfillment, returns, warranties, and customer service apply to your visit and transaction. WantCove will place a plain-language affiliate disclosure near each active compensated link.</p></LegalSection>
    <LegalSection title="4. Accounts and saved content"><p>If accounts are enabled, you are responsible for protecting your credentials and for activity under your account. You may only save content you are authorized to use. WantCove may suspend access needed to protect users, the service, or comply with law. More detailed account and deletion terms must be added before authentication is released.</p></LegalSection>
    <LegalSection title="5. Acceptable use"><p>Do not interfere with WantCove, bypass security controls, scrape or automate access contrary to published instructions, upload malicious code, misuse another person’s account, or use the service unlawfully.</p></LegalSection>
    <LegalSection title="6. Intellectual property"><p>WantCove’s name, interface, original text, and original media are protected by applicable intellectual-property laws. Retailer and product names or marks belong to their respective owners and do not imply sponsorship or endorsement.</p></LegalSection>
    <LegalSection title="7. Disclaimers and responsibility"><p>To the extent permitted by law, WantCove is provided “as is” and “as available.” WantCove does not guarantee that third-party product information is complete, current, or error-free. Any limitations of liability, governing-law terms, and dispute process must be reviewed for the operator’s jurisdiction before Production.</p></LegalSection>
    <LegalSection title="8. Changes"><p>WantCove may update these Terms when the service or legal requirements change. Material updates will receive a new effective date and will be recorded in the project’s release history before deployment.</p></LegalSection>
    <LegalSection title="9. Contact"><p>A monitored legal contact method and the legal identity of the WantCove operator will be published here before Beta enables accounts or commercial affiliate links.</p></LegalSection>
  </LegalDocument>
}
