import { LegalDocument, LegalSection } from '../components/LegalDocument'

export function TermsPage() {
  return <LegalDocument eyebrow="Legal" title="Terms of Service" summary="These terms explain the rules for browsing WantCove and using its product-discovery and like features.">
    <LegalSection title="1. Using WantCove"><p>By accessing WantCove, you agree to these Terms. If you do not agree, do not use the service. WantCove is intended for people who can legally enter into these Terms. Additional eligibility language will be added before public user accounts are opened.</p></LegalSection>
    <LegalSection title="2. Product discovery, not a retailer"><p>WantCove helps users discover and like products. WantCove does not currently sell, manufacture, ship, warrant, or process payment for the products shown. Product descriptions, prices, ratings, availability, and images are informational and may change. Verify material details with the retailer before purchasing.</p></LegalSection>
    <LegalSection title="3. External and affiliate links"><p><strong>As an Amazon Associate I earn from qualifying purchases.</strong></p><p>Some product links may include an affiliate or referral code. If you click one of those links and make a purchase, WantCove may receive a commission at no additional cost to you. Affiliate compensation does not increase the price charged by WantCove because WantCove is not the seller.</p><p>Clicking a retailer link takes you away from WantCove. The retailer&apos;s own terms, privacy policy, pricing, fulfillment, returns, warranties, and customer service apply to your visit and transaction. WantCove will place a plain-language affiliate disclosure near each active compensated link. Commercial retailer links remain disabled during this pre-release stage.</p></LegalSection>
    <LegalSection title="4. Likes and accounts"><p>You may like a product without creating an account. A like is a preference signal for your own convenience; it is not a product rating, purchase, endorsement, or public statement. Anonymous likes may be lost when browser identity data is cleared and are set to expire after a limited period.</p><p>Public user registration is not enabled. Restricted administrative accounts exist only to operate the catalog and are not a public feature. Administrators must protect their credentials, authenticator, and email recovery channel. Password recovery does not remove MFA, grant ADMINS membership, or authorize catalog access by itself. If public accounts are enabled later, more detailed account and deletion terms will be added first.</p></LegalSection>
    <LegalSection title="5. Acceptable use"><p>Do not interfere with WantCove, bypass security controls, manipulate likes, create identities to evade safeguards, scrape or automate access contrary to published instructions, upload malicious code, misuse another person&apos;s account, or use the service unlawfully.</p></LegalSection>
    <LegalSection title="6. Intellectual property"><p>WantCove&apos;s name, interface, original text, and original media are protected by applicable intellectual-property laws. Retailer and product names or marks belong to their respective owners and do not imply sponsorship or endorsement.</p></LegalSection>
    <LegalSection title="7. Disclaimers and responsibility"><p>To the extent permitted by law, WantCove is provided “as is” and “as available.” WantCove does not guarantee that third-party product information is complete, current, or error-free. Any limitations of liability, governing-law terms, and dispute process must be reviewed for the operator&apos;s jurisdiction before Production.</p></LegalSection>
    <LegalSection title="8. Changes"><p>WantCove may update these Terms when the service or legal requirements change. Material updates will receive a new effective or updated date and will be recorded in the project&apos;s release history before deployment.</p></LegalSection>
    <LegalSection title="9. Contact"><p>A monitored legal contact method and the legal identity of the WantCove operator will be published here before Beta enables public user accounts or commercial affiliate links.</p></LegalSection>
  </LegalDocument>
}
